name: push validation
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: :app:assemble
      run: ./gradlew assemble -PclientID=${{ secrets.clientID }}
      shell: bash